apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  annotation : metallb.universe.tf/allow-shared-ip
spec:
  selector:
    app: grafana
  ports:
    - name: grafana
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer