apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  annotation : metallb.universe.tf/allow-shared-ip
spec:
  selector:
    app: phpmyadmin
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer