apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  annotation : metallb.universe.tf/allow-shared-ip
spec:
  selector:
    app: wordpress
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5050
  type: LoadBalancer