apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  annotation : metallb.universe.tf/allow-shared-ip
spec:
  selector:
    app: influxdb
  ports:
    - name: influxdb
      protocol: TCP
      port: 8086
      targetPort: 8086
  type: ClusterIP